- name: obtain NIC names
  shell: >-
    ip -o route get {{ item.bindnetaddr }} | sed -e "s/^.*\sdev\s\([^\s]*\)\s.*$/\1/"
  register: ip_result
  changed_when: false
  with_items: "{{ INTERFACES }}"

# equivalent to {{ ip_result.results|map('stdout')|list }}
# map() is available in Python 2.7 or later, but we still try to support RHEL6 yet.
- name: map NIC names list
  set_fact:
    nics: "{{ nics|default([]) + [ item.stdout ] }}"
  changed_when: false
  with_items: "{{ ip_result.results }}"
  loop_control:
    label: "{{ item.stdout }}" # to suppress too verbose logs

#- debug:
#    var: nics

## # iptables -D INPUT -i {{ NIC }} -j DROP ; iptables -D OUTPUT -o {{ NIC }} -j DROP
- name: disconnect Corosync communication (via iptables)
  shell: >-
    iptables -D INPUT -i {{ item }} -j DROP ; iptables -D OUTPUT -o {{ item }} -j DROP
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and "Bad rule" not in result.stderr
  with_items: "{{ nics }}"

#- debug:
#    var: result
