- include: rsyslog-unconfig-rhel6.yml
  when: ansible_distribution_major_version == '6'
- include: rsyslog-unconfig-rhel7.yml
  when: ansible_distribution_major_version == '7'

- include: tools-disable-rhel6.yml
  when: ansible_distribution_major_version == '6'
- include: tools-disable-rhel7.yml
  when: ansible_distribution_major_version == '7'
