- name: check if Pacemaker service is presented (RHEL7)
  stat:
    path=/etc/systemd/system/pacemaker.service
  register: pacemaker_service_file

- name: stop Pacemaker service if exists (RHEL7)
  service:
    name="pacemaker"
    state=stopped
  when: pacemaker_service_file.stat.exists == True
